// The fifteen documents.
//
// The player never picks one up. They are a student standing in front of a
// primary source, so they do the only thing available: copy it down. That
// needs no time-travel rule and no explanation.
//
// ---------------------------------------------------------------------
// A NOTE ON FIDELITY, WHICH MATTERS MORE HERE THAN ANYWHERE ELSE
//
// Presenting invented text to a student as a quotation from a primary
// source would be a worse sin than anything else this game could do. So
// every document carries a `fidelity` field, shown on the reader screen:
//
//   'close'         follows the surviving document closely in substance and
//                   largely in wording. Still check against the archive
//                   before this goes in front of a class.
//   'reconstructed' written in the form and language of the record — warrant
//                   formulas, account-book conventions, the standard clauses
//                   — but not a transcription of one specific surviving
//                   sheet. The substance is documented; the exact wording is
//                   a rendering.
//
// The distinction is displayed to the player, on purpose. A student noticing
// that some sources are transcriptions and some are reconstructions is a
// student doing source criticism, which is the entire point.
//
// Everything here should be checked against Bernard Rosenthal, *Records of
// the Salem Witch-Hunt* (Cambridge, 2009), and the Salem Witch Trials
// Documentary Archive at the University of Virginia, both cited on screen.
// ---------------------------------------------------------------------

export const DOCUMENTS = {

  /* ---------------------------------------------------------------- *
   * March — money, land, and status, all in writing
   * ---------------------------------------------------------------- */

  parrisAgreement: {
    id: 'parrisAgreement',
    title: 'The village agreement with Mr. Parris',
    date: '1689',
    kind: 'A signature',
    fidelity: 'reconstructed',
    cite: 'Salem Village Book of Record, 1689. See Rosenthal, Records of the Salem Witch-Hunt.',
    note: 'The promise, in writing, that the village then broke.',
    original: [
      'Agreed with Mr Samuel Parris to take the office of the ministry',
      'among us, upon these termes following:',
      '',
      'First, that he is to have Sixty six pounds for his yearly',
      'salary, one third part in money, and the other two third',
      'parts in provisions at these prices following, viz: Indian',
      'corn at two shillings a bushell, Rye at three shillings,',
      'Barley at three shillings, Beefe at three pence per pound,',
      'Porke at two pence per pound, Butter at six pence.',
      '',
      'Item: that his fire wood be given in freely to him.',
      '',
      'Item: that the Ministry house and barne be kept in good',
      'repaire, and the land improved for his use.',
    ],
    gloss: [
      'The village hired Samuel Parris as minister on these terms.',
      '',
      'Sixty-six pounds a year. Only a third of it in actual money —',
      'the rest paid in corn, rye, barley, beef, pork and butter, at',
      'fixed prices written into the contract.',
      '',
      'AND: his firewood supplied free.',
      '',
      'AND: the parsonage and barn kept in repair for him.',
      '',
      'Two years later the village elected a committee that stopped',
      'collecting the tax that paid the salary, and stopped delivering',
      'the wood.',
      '',
      'His woodpile is outside. Go and count it.',
    ],
  },

  seatingList: {
    id: 'seatingList',
    title: 'Seating of the meeting house',
    date: '1690',
    kind: 'A number',
    fidelity: 'reconstructed',
    cite: 'Salem Village Book of Record. Seating committees and their lists are documented throughout the 1680s–90s.',
    note: 'Status, priced. Nailed where everyone reads it twice a week.',
    original: [
      'The Committee chosen to seat the meeting house, having',
      'regard to age, to office, and to what each man payeth to',
      'the rates, do order the seating as followeth:',
      '',
      '  In the foremost seat        Capt. Jonathan Walcott    £2  4s',
      '                              Mr Thomas Putnam          £2  1s',
      '                              Mr Nathaniel Ingersoll    £1 18s',
      '  In the second seat          Goodman Francis Nurse     £1  6s',
      '                              Goodman Peter Cloyse      £1  2s',
      '  In the third seat           Goodman John Willard         14s',
      '  ...',
      '  In the hindmost seat        Sarah Good                 —',
    ],
    gloss: [
      'A committee decided where every household in the village sat',
      'in church, based on age, office, and — written right beside',
      'each name — how much tax that household paid.',
      '',
      'The wealthiest men sit at the front. Everyone else is placed',
      'behind them in descending order of what they are worth.',
      '',
      'The list is nailed to the wall by the door.',
      '',
      'Twice every Sunday, for hours, the entire village sits down',
      'in the exact order of who matters. Nobody has to be told',
      'where they stand.',
      '',
      'The last name on the list has no sum beside it at all.',
    ],
  },

  accountBookPage: {
    id: 'accountBookPage',
    title: "A page of Ingersoll's account book",
    date: '1691–92',
    kind: 'A number',
    fidelity: 'reconstructed',
    cite: 'Ordinary-keepers\' account books of the period; the Putnams\' extensive credit in the village is documented in Boyer & Nissenbaum, Salem Possessed.',
    note: 'Debt as a map of who cannot afford to disagree.',
    original: [
      '            Dr.                                    Cr.',
      '  Jno. Willard      for seed corn      1  4  0   Putnam',
      '  Jos. Herrick      for timber         2 11  6   Putnam',
      '  Wm. Sibley        cattle wintered    3  0  0   Putnam',
      '  Sar. Bibber       for meal              9  0   Ingersoll',
      '  Jno. Procter      for cider          1  2  0   Ingersoll',
      '  Geo. Jacobs       for oxen hire      1 15  0   Putnam',
      '  Isr. Porter       —                     —      —',
    ],
    gloss: [
      'Who owes what, and to whom.',
      '',
      'Read down the right-hand column — the people the money is owed',
      'TO — and one surname keeps appearing. Seed corn, timber, cattle',
      'wintered over, the hire of oxen.',
      '',
      'This is not wickedness. It is what a large family with land and',
      'money does in a small farming place.',
      '',
      'But it means that when a Putnam says something in this village,',
      'a great many people have a concrete financial reason not to',
      'contradict him.',
      '',
      'One name in this column owes them nothing: Porter.',
    ],
  },

  topsfieldPetition: {
    id: 'topsfieldPetition',
    title: 'Petition concerning the Topsfield line',
    date: '1680s',
    kind: 'A signature',
    fidelity: 'reconstructed',
    cite: 'The Topsfield–Salem Village boundary dispute ran from the 1660s; see Boyer & Nissenbaum, Salem Possessed, ch. 3.',
    note: 'A land quarrel thirty years old, with the same families on each side.',
    original: [
      'To the Honoured Generall Court:',
      '',
      'The humble petition of severall of the inhabitants of Salem',
      'Village sheweth, that whereas the men of Topsfield have of',
      'late yeares presumed to lay out and to fell timber upon lands',
      'which were granted unto Salem long before Topsfield was a',
      'towne, and have carried away the same,',
      '',
      'We pray this Honoured Court would settle the bounds,',
      '',
      '        Thomas Putnam        John Putnam',
      '        Nathaniel Putnam     Edward Putnam',
      '        Jonathan Walcott     ...',
      '',
      'Contra, for Topsfield:',
      '        Jacob Towne          John Towne',
      '        Isaac Easty          Joseph Towne',
    ],
    gloss: [
      'A land dispute between Salem Village and the neighbouring town',
      'of Topsfield, over a boundary and the timber cut on it.',
      '',
      'It had already been running for twenty years when this was',
      'written, and it would run for twenty more.',
      '',
      'Look at the two lists of names.',
      '',
      'On one side, the Putnams.',
      '',
      'On the other, the Townes and the Eastys. Rebecca Nurse was born',
      'a Towne. Mary Easty is her sister.',
      '',
      'In 1692, all three Towne sisters — Rebecca Nurse, Mary Easty,',
      'and Sarah Cloyce — were accused of witchcraft.',
    ],
  },

  /* ---------------------------------------------------------------- *
   * June — the machinery
   * ---------------------------------------------------------------- */

  nurseWarrant: {
    id: 'nurseWarrant',
    title: 'Warrant for the arrest of Rebecca Nurse',
    date: '23 March 1692',
    kind: 'A signature',
    fidelity: 'close',
    cite: 'Warrant for the apprehension of Rebecca Nurse, 23 March 1692. Essex County Court Archives, Salem Witchcraft, vol. 1.',
    note: 'The machinery starting. It is a printed-form kind of document.',
    original: [
      'Salem, March the 23d, 1691/2',
      '',
      'To the Marshall of Essex or his lawfull Deputie:',
      '',
      'You are in theire Majest\'s names hereby required to bring',
      'before us Rebekah Nurse the wife of Franc\'s Nurse of Salem',
      'Village, tomorrow about eight of the clock in the forenoon,',
      'at the house of Lt Nathaniell Ingersalls in s\'d Village,',
      '',
      'who stands charged with haveing committed sundry acts of',
      'Witchcraft, and thereby haveing done much hurt and injury',
      'to the bodys of Ann Putnam the wife of Thomas Putnam of',
      'Salem Village, Ann Putnam junr, and Abigail Williams &c.,',
      '',
      'and hereof faile not.',
      '',
      '                        John Hathorne  }  Assists',
      '                        Jonathan Corwin }',
    ],
    gloss: [
      'An arrest warrant, issued the day before she was taken.',
      '',
      'Notice where she is ordered to be brought: to Ingersoll\'s.',
      'The tavern. There was nowhere else big enough.',
      '',
      'Notice who is named as the injured party. Ann Putnam senior.',
      'Ann Putnam junior. Abigail Williams. The "&c." at the end is',
      'the clerk not bothering to list the rest.',
      '',
      'Notice the date written as "1691/2". England had not yet moved',
      'the start of the year from March to January.',
      '',
      'Rebecca Nurse was seventy-one, ill in bed, and a covenanted',
      'member of the church in Salem Town.',
      '',
      'She was arrested the next morning.',
    ],
  },

  nursePetition: {
    id: 'nursePetition',
    title: 'The petition for Rebecca Nurse',
    date: '1692',
    kind: 'Thirty-nine signatures',
    fidelity: 'close',
    cite: 'Petition for Rebecca Nurse, 1692. Essex County Court Archives, Salem Witchcraft, vol. 1.',
    note: 'The whole village saying she is not a witch, and it not mattering.',
    original: [
      'We whose names are here unto subscribed being desired by',
      'Goodman Nurse to declare what we knowe concerning his wifes',
      'conversation for time past, we can testifie to all whom it may',
      'concerne, that we have knowne her for many yeares, and',
      'accordinge to our observation her Life and conversation was',
      'accordinge to her profession, and we never had any cause or',
      'grounds to suspect her of any such thinge as she is nowe',
      'accused of.',
      '',
      '  Israel Porter          Elizabeth Porter',
      '  Edward Bishop Sr       Hannah Bishop',
      '  Joshua Rea             Sarah Rea',
      '  Sarah Leach            John Putnam Sr',
      '  Rebecca Putnam         Joseph Hutchinson',
      '  ... and twenty-nine others',
    ],
    gloss: [
      'Thirty-nine of her neighbours signed a statement saying they',
      'had known this woman for years and had never seen anything in',
      'her life to suggest she was what she was accused of being.',
      '',
      'Read the names carefully.',
      '',
      'John Putnam Sr. Rebecca Putnam.',
      '',
      'Even inside the family driving the accusations, people signed',
      'for her. This was not a village united against an outcast.',
      '',
      'The jury acquitted her.',
      '',
      'The courtroom erupted. The judges asked the jury to reconsider',
      'a phrase she had used. They went back out. They came back and',
      'convicted her.',
      '',
      'She was hanged on 19 July 1692.',
    ],
  },

  putnamDeposition: {
    id: 'putnamDeposition',
    title: 'Deposition of Ann Putnam, junior',
    date: '1692',
    kind: 'Not meant for you',
    fidelity: 'reconstructed',
    cite: 'Depositions of Ann Putnam Jr., 1692. Many surviving examples are in the hand of her father, Thomas Putnam.',
    note: 'Spectral evidence, sworn by a twelve-year-old. Look at the handwriting.',
    original: [
      'The deposition of Ann Putnam junr who testifieth and saith:',
      '',
      'That on the 13th of March 1692 I saw the Apperishtion of',
      'Rebekah Nurse, and she did most greviously torment me by',
      'pinching and pricking me most dreadfully,',
      '',
      'and so she hath severall times sence tortored me, urging me',
      'vehemently to writ in her book,',
      '',
      'and I veryly beleve in my heart that Rebekah Nurse is a',
      'wicth and that she hath severall times afflected me.',
      '',
      '  Ann Putnam junr declared the above written evidence to be',
      '  the truth upon her oath before the Jurors of Inquest.',
    ],
    gloss: [
      'Sworn testimony that the SHAPE of Rebecca Nurse — her spirit,',
      'her apparition — came into a room and hurt a twelve-year-old.',
      '',
      'Nobody else could see it. There was no possible way to disprove',
      'it. This is spectral evidence, and the court accepted it.',
      '',
      'Now look at the document itself rather than the words.',
      '',
      'Ann Putnam Jr. is twelve. She did not write this. A great many',
      'of the depositions sworn by the afflicted girls survive in the',
      'handwriting of one man — Thomas Putnam, Ann\'s father, who filed',
      'more complaints than almost anyone in the county.',
      '',
      'She swore to it. He wrote it.',
      '',
      'In 1706 she stood in the village church while her apology for',
      'this was read aloud over her head.',
    ],
  },

  jailBill: {
    id: 'jailBill',
    title: "The jail keeper's account",
    date: '1692',
    kind: 'A number',
    fidelity: 'reconstructed',
    cite: 'Prison charges are documented in the 1692 accounts and in later restitution claims; see Rosenthal, Records of the Salem Witch-Hunt.',
    note: 'They were charged for their own imprisonment. Including the irons.',
    original: [
      'The account of the keeper of their Majesties Gaol in Salem,',
      'for the dyett and necessaries of persons committed upon',
      'suspicion of witchcraft:',
      '',
      '  To dyett, 9 weeks, at 2s 6d the week          1  2  6',
      '  To the chains and shackles                        6  8',
      '  To fees at commitment                             2  0',
      '  To fees at discharge                              2  0',
      '  To the removing of the body                       5  0',
      '',
      '  Note: no prisoner to be released until the said',
      '  charges be satisfied, either by the prisoner or',
      '  by their friends.',
    ],
    gloss: [
      'Prison in 1692 was not free. The accused were billed for their',
      'own food, their own fees, and — read it again — their own',
      'chains.',
      '',
      'And nobody was released until the bill was paid. Several people',
      'who were found not guilty stayed in jail for months afterwards',
      'because their families could not settle the account.',
      '',
      'The last line is a charge for moving a body.',
      '',
      'Sarah Good gave birth in this jail. The baby died there.',
      '',
      'Whatever else was going on in 1692, somebody was being paid.',
    ],
  },

  /* ---------------------------------------------------------------- *
   * September — the end of it
   * ---------------------------------------------------------------- */

  eastyPetition: {
    id: 'eastyPetition',
    title: 'The petition of Mary Easty',
    date: 'September 1692',
    kind: 'Not meant for you',
    fidelity: 'close',
    cite: 'Petition of Mary Easty to the Court, September 1692. Essex County Court Archives, Salem Witchcraft, vol. 2.',
    note: 'She is not asking for her life.',
    original: [
      'The humble petition of Mary Easty unto his Excellencyes Sir',
      'William Phipps, and to the honoured Judge and Bench now',
      'sitting in Judicature in Salem:',
      '',
      'I petition to your honours not for my own life, for I know I',
      'must die, and my appointed time is set,',
      '',
      'but the Lord he knowes it is that, if it be possible, no more',
      'innocent blood may be shed, which undoubtedly cannot be',
      'avoyded in the way and course you goe in.',
      '',
      'I question not but your honours does to the utmost of your',
      'powers in the discovery and detecting of witchcraft and',
      'witches, and would not be gulty of innocent blood for the',
      'world.',
      '',
      'But by my own innocency I know you are in the wrong way.',
    ],
    gloss: [
      'Mary Easty was Rebecca Nurse\'s sister. She was arrested,',
      'released, and re-arrested after the afflicted girls insisted.',
      '',
      'She wrote this knowing she was going to be hanged.',
      '',
      'Read what she asks for. Not her life — she says plainly that',
      'she knows she must die. She asks that the court change its',
      'methods so that it stops killing other people.',
      '',
      'And read how she says it. She does not accuse the judges of',
      'malice. She says she is sure they are doing their best and',
      'would not shed innocent blood for the world.',
      '',
      'Then: "But by my own innocency I know you are in the wrong way."',
      '',
      'She was hanged on 22 September 1692.',
    ],
  },

  coreyRecord: {
    id: 'coreyRecord',
    title: 'The court record: Giles Corey stands mute',
    date: '19 September 1692',
    kind: 'A number',
    fidelity: 'reconstructed',
    cite: 'The pressing of Giles Corey, 19 September 1692; recorded by Samuel Sewall in his diary and in the court records.',
    note: 'Two days. Follow the money.',
    original: [
      'Giles Corey, being indicted for witchcraft, was this day',
      'brought before the Court, and being called upon to plead',
      'unto his indictment, refused to plead, standing mute.',
      '',
      'Being three times required to plead, and three times refusing,',
      'sentence of peine forte et dure was passed upon him,',
      '',
      'that he be pressed with weights until he plead or die.',
      '',
      '  Monday, Sept. 19, 1692. About noon, at Salem, Giles Corey',
      '  was press\'d to death for standing Mute.',
      '                                     — S. Sewall, his diary',
    ],
    gloss: [
      'Under English law, a trial could not proceed until the accused',
      'entered a plea. If you refused to plead, the court could order',
      'you crushed under stones until you did.',
      '',
      'Giles Corey was eighty-one. He refused three times. It took',
      'two days.',
      '',
      'Now the part that is not about courage.',
      '',
      'If you were tried and convicted of a felony, the Crown could',
      'seize your estate. If you were never tried — because you never',
      'pleaded — it could not.',
      '',
      'By refusing to plead, Giles Corey kept his farm out of the',
      'sheriff\'s hands and left it to his sons-in-law.',
      '',
      'He worked out what it would cost him and he paid it.',
    ],
  },

  seizureInventory: {
    id: 'seizureInventory',
    title: "Inventory of goods seized by the Sheriff",
    date: '1692',
    kind: 'A number',
    fidelity: 'reconstructed',
    cite: 'Seizures by Sheriff George Corwin are documented in later restitution petitions, 1710–11.',
    note: 'What the law took out of a household while the family was in jail.',
    original: [
      'An account of what was seized and carried away by the Sheriff',
      'from the house of a person condemned:',
      '',
      '  5 cows                                    12  0  0',
      '  a yoke of oxen                             8  0  0',
      '  8 loads of English hay                     4  0  0',
      '  a quantity of provisions, meat and corn     3 10  0',
      '  brass and pewter out of the house           2  4  0',
      '  the beds                                    1 16  0',
      '',
      '  Also, a barrel of cider carried away, and the',
      '  wife left with nothing to keep the children.',
    ],
    gloss: [
      'When someone was convicted, the sheriff came to the house and',
      'took what was in it.',
      '',
      'The cattle. The oxen — which is to say the ability to plough.',
      'The hay that would have fed the animals through winter. The',
      'food. The pewter. The beds.',
      '',
      'The family left behind was not accused of anything.',
      '',
      'Twenty years later, survivors petitioned the government for',
      'restitution. Some got money. Some did not. Several of the',
      'petitions describe a household that never recovered.',
      '',
      'When you are working out what caused 1692, this is one of the',
      'things you have to weigh: some people ended up better off.',
    ],
  },

  deathWarrantReturn: {
    id: 'deathWarrantReturn',
    title: 'Return upon the death warrant',
    date: '22 September 1692',
    kind: 'A signature',
    fidelity: 'reconstructed',
    cite: 'Execution returns, September 1692. Eight people were hanged on 22 September, the last executions of the episode.',
    note: 'Eight people. One line each.',
    original: [
      'According to the within written precept, I have taken the',
      'bodyes of the persons within named and caused them to be',
      'hanged by the neck untill they were dead,',
      '',
      '  Martha Corey            Mary Easty',
      '  Alice Parker            Mary Parker',
      '  Ann Pudeator            Wilmot Redd',
      '  Margaret Scott          Samuel Wardwell',
      '',
      'and have made return hereof.',
      '',
      '                        George Corwin, Sheriff',
    ],
    gloss: [
      'Eight people, on one morning, on a ledge above the town.',
      '',
      'This is the paperwork afterwards. A sheriff confirming to a',
      'court that an instruction has been carried out. The form is',
      'the same form used for any writ.',
      '',
      'Nobody knew it at the time, but these were the last executions.',
      'Within weeks the court had been dissolved. Within months',
      'spectral evidence was disallowed. Within five years people who',
      'had taken part were apologising in public.',
      '',
      'Read the eight names again, and then go and look at the benches.',
    ],
  },

  /* ---------------------------------------------------------------- *
   * The present — the reckoning
   * ---------------------------------------------------------------- */

  annApology: {
    id: 'annApology',
    title: 'The confession of Ann Putnam, junior',
    date: '1706',
    kind: 'A signature',
    fidelity: 'close',
    cite: 'Ann Putnam Jr.\'s confession, read aloud in Salem Village church by Rev. Joseph Green, 1706.',
    note: 'She was twelve when you met her. She is twenty-six here.',
    original: [
      'I desire to be humbled before God for that sad and humbling',
      'providence that befell my father\'s family in the year about',
      'ninety-two;',
      '',
      'that I, then being in my childhood, should, by such a',
      'providence of God, be made an instrument for the accusing of',
      'several persons of a grievous crime, whereby their lives were',
      'taken away from them, whom now I have just grounds and good',
      'reason to believe they were innocent persons;',
      '',
      'and that it was a great delusion of Satan that deceived me in',
      'that sad time, whereby I justly fear I have been instrumental,',
      'with others, though ignorantly and unwittingly, to bring upon',
      'myself and this land the guilt of innocent blood;',
      '',
      'though what was said or done by me against any person I can',
      'truly and uprightly say, before God and man, I did it not out',
      'of any anger, malice, or ill-will to any person, for I had no',
      'such thing against one of them; but what I did was ignorantly,',
      'being deluded of Satan.',
      '',
      'And particularly, as I was a chief instrument of accusing of',
      'Goodwife Nurse and her two sisters, I desire to lie in the',
      'dust, and to be humbled for it, in that I was a cause, with',
      'others, of so sad a calamity to them and their families.',
    ],
    gloss: [
      'Fourteen years later, Ann Putnam Jr. stood in the meeting house',
      'in Salem Village while the minister read this out over her head',
      'in front of the congregation.',
      '',
      'She is the only one of the afflicted girls who ever did this.',
      '',
      'Read what she does and does not say. She says she was wrong.',
      'She says the people she accused were innocent. She names',
      'Rebecca Nurse specifically, and her sisters.',
      '',
      'She also says she was deluded by Satan, and that she bore no',
      'malice to any of them. Whether you believe that part is a',
      'genuine historical question, and historians disagree about it.',
      '',
      'She never married. She raised her younger siblings after both',
      'her parents died within two weeks of each other in 1699.',
      '',
      'She died at thirty-seven and is buried in an unmarked grave.',
      '',
      'You met her when she was twelve, mending something by a window,',
      'complaining that people came to stare.',
    ],
  },

  sewallApology: {
    id: 'sewallApology',
    title: 'The bill of Samuel Sewall',
    date: '14 January 1697',
    kind: 'A signature',
    fidelity: 'close',
    cite: 'Samuel Sewall\'s bill of apology, read at Old South Church, Boston, 14 January 1697, by Rev. Samuel Willard.',
    note: 'One judge out of nine.',
    original: [
      'Samuel Sewall, sensible of the reiterated strokes of God upon',
      'himself and family, and being sensible that as to the guilt',
      'contracted upon the opening of the late commission of Oyer and',
      'Terminer at Salem,',
      '',
      'he is, upon many accounts, more concerned than any that he',
      'knows of,',
      '',
      'desires to take the blame and shame of it, asking pardon of',
      'men, and especially desiring prayers that God, who has an',
      'unlimited authority, would pardon that sin and all other his',
      'sins.',
    ],
    gloss: [
      'Five years after the trials, one of the judges stood up in a',
      'church in Boston on a public fast day while the minister read',
      'this aloud, and he stood the whole time.',
      '',
      'He kept a fast day for it every year for the rest of his life.',
      'He later wrote one of the first anti-slavery tracts published',
      'in America.',
      '',
      'Now the other half of this document, which is not written down',
      'anywhere because it never happened:',
      '',
      'William Stoughton was the chief justice. He was the one who',
      'admitted spectral evidence in the first place, and the one who',
      'sent the jury back out when they acquitted Rebecca Nurse.',
      '',
      'He never apologised, never expressed a doubt, and was angry',
      'when the trials were stopped.',
      '',
      'He became governor of Massachusetts. There is a county named',
      'after him.',
    ],
  },

  johnsonAct: {
    id: 'johnsonAct',
    title: 'An Act relative to Elizabeth Johnson Jr.',
    date: '2022',
    kind: 'A signature',
    fidelity: 'close',
    cite: 'Massachusetts Session Laws, 2022. Added as an amendment to the state budget after a campaign by an eighth-grade civics class in North Andover.',
    note: 'Written by thirteen-year-olds.',
    original: [
      'SECTION —.  The conviction and sentence of Elizabeth Johnson,',
      'Jr., of the crime of witchcraft in the year sixteen hundred',
      'and ninety-three are hereby declared null and void.',
      '',
      'The names of all persons convicted of witchcraft in the years',
      'sixteen hundred and ninety-two and sixteen hundred and ninety-',
      'three, and their heirs, are hereby declared free from any and',
      'all disgrace or cause of distress.',
    ],
    gloss: [
      'Elizabeth Johnson Jr. was convicted, sentenced to hang, and',
      'never executed. Then she was simply forgotten.',
      '',
      'Massachusetts cleared the others in stages — 1711, 1957, 1992,',
      '2001 — and each time she was left off the list. She had no',
      'descendants, so nobody was left to be annoyed about it.',
      '',
      'She stayed a convicted witch for three hundred and twenty-nine',
      'years.',
      '',
      'In 2021 an eighth-grade civics class in North Andover found',
      'out. They did the research, drafted the bill, and persuaded a',
      'state senator to file it. It passed as an amendment to the',
      'state budget in 2022.',
      '',
      'This is the most recent document in this game, and the people',
      'who wrote it were younger than you are.',
    ],
  },
};

/** Documents grouped by the chapter they can first be copied in. */
export const DOCS_BY_CHAPTER = {
  march: ['parrisAgreement', 'seatingList', 'accountBookPage', 'topsfieldPetition'],
  june: ['nurseWarrant', 'nursePetition', 'putnamDeposition', 'jailBill'],
  september: ['eastyPetition', 'coreyRecord', 'seizureInventory', 'deathWarrantReturn'],
  present: ['annApology', 'sewallApology', 'johnsonAct'],
};

export const DOC_COUNT = Object.keys(DOCUMENTS).length;

export const FIDELITY_LABEL = {
  close: 'Follows the surviving document closely',
  reconstructed: 'Reconstructed in the form of the record',
};
